const data = [
    {
        pokemonType:'Bug',
        effectiveAgainst:['Dark','Psychic','Grass'],
        weakAgainst:['Fire','Rock','Flying'],
        resistance:['Fighting','Ground','Grass'],
        immuneDMG:[],
        immuneATK:[]
    },
    {
        pokemonType:'Normal',
        effectiveAgainst:[],
        weakAgainst:['Fighting'],
        resistance:[],
        immuneDMG:['Ghost'],
        immuneATK:['Ghost']
    },
    {
        pokemonType:'Dragon',
        effectiveAgainst:['Dragon'],
        weakAgainst:['Dragon','Fairy','Ice'],
        resistance:['Water','Grass','Electric','Fire'],
        immuneDMG:[],
        immuneATK:['Fairy']
    },
    {
        pokemonType:'Dark',
        effectiveAgainst:['Ghost','Psychic'],
        weakAgainst:['Bug','Fighting','Fairy'],
        resistance:['Ghost','Dark'],
        immuneDMG:['Psychic'],
        immuneATK:[]
    },
    {
        pokemonType:'Electric',
        effectiveAgainst:['Water','Flying'],
        weakAgainst:['Grass','Rock','Ground'],
        resistance:['Flying','Steel','Electric'],
        immuneDMG:[],
        immuneATK:['Ground']
    },
    {
        pokemonType:'Fairy',
        effectiveAgainst:['Fighting','Dragon','Dark'],
        weakAgainst:['Poison','Steel'],
        resistance:['Fighting','Bug','Dark'],
        immuneDMG:['Dragon'],
        immuneATK:[]
    },
    {
        pokemonType:'Fighting',
        effectiveAgainst:['Normal','Ice','Dark','Steel','Rock'],
        weakAgainst:['Flying','Psychic','Fairy'],
        resistance:['Rock','Bug','Dark'],
        immuneDMG:[],
        immuneATK:['Ghost']
    },
    {
        pokemonType:'Fire',
        effectiveAgainst:['Grass','Ice','Steel','Bug'],
        weakAgainst:['Water','Rock','Ground'],
        resistance:['Bug','Steel','Fire','Grass','Ice'],
        immuneDMG:[],
        immuneATK:[]
    },
    {
        pokemonType:'Flying',
        effectiveAgainst:['Grass','Fighting','Bug'],
        weakAgainst:['Electric','Rock','Ice'],
        resistance:['Fighting','Bug','Grass'],
        immuneDMG:['Ground'],
        immuneATK:[]
    },
    {
        pokemonType:'Ghost',
        effectiveAgainst:['Ghost','Psychic'],
        weakAgainst:['Ghost','Dark'],
        resistance:['Poison','Bug'],
        immuneDMG:['Fighting','Normal'],
        immuneATK:['Normal']
    },
    {
        pokemonType:'Grass',
        effectiveAgainst:['Water','Ground','Rock'],
        weakAgainst:['Flying','Poison','Fire','Bug','Ice'],
        resistance:['Ground','Water','Grass','Electric'],
        immuneDMG:[],
        immuneATK:[]
    },
    {
        pokemonType:'Ground',
        effectiveAgainst:['Fire','Steel','Electric','Poison','Rock'],
        weakAgainst:['Water','Ice','Grass'],
        resistance:['Poison','Rock'],
        immuneDMG:['Electric'],
        immuneATK:['Flying']
    },
    {
        pokemonType:'Ice',
        effectiveAgainst:['Grass','Flying','Dragon','Ground'],
        weakAgainst:['Fire','Steel','Rock','Fighting'],
        resistance:['Ice'],
        immuneDMG:[],
        immuneATK:[]
    },
    {
        pokemonType:'Poison',
        effectiveAgainst:['Fairy','Grass'],
        weakAgainst:['Ground','Psychic'],
        resistance:['Fighting','Poison','Grass','Fairy'],
        immuneDMG:[],
        immuneATK:['Steel']
    },
    {
        pokemonType:'Psychic',
        effectiveAgainst:['Fighting','Poison'],
        weakAgainst:['Dark','Ghost','Bug'],
        resistance:['Fighting','Psychic'],
        immuneDMG:[],
        immuneATK:['Dark']
    },
    {
        pokemonType:'Rock',
        effectiveAgainst:['Flying','Bug','Ice','Fire'],
        weakAgainst:['Grass','Water','Ground','Steel','Fighting'],
        resistance:['Normal','Flying','Poison','Fire'],
        immuneDMG:[],
        immuneATK:[]
    },
    {
        pokemonType:'Steel',
        effectiveAgainst:['Fairy','Rock','Ice'],
        weakAgainst:['Fire','Fighting','Ground'],
        resistance:['Normal','Flying','Rock','Bug','Steel','Grass','Psychic','Ice','Dragon','Fairy'],
        immuneDMG:['Poison'],
        immuneATK:[]
    },
    {
        pokemonType:'Water',
        effectiveAgainst:['Fire','Rock','Ground'],
        weakAgainst:['Electric','Grass'],
        resistance:['Steel','Water','Fire','Ice'],
        immuneDMG:[],
        immuneATK:[]
    }
]

module.exports = data